# Generated by Django 3.2.12 on 2022-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('platform', models.CharField(choices=[('A', 'All'), ('T', 'Telegram'), ('D', 'Discord')], max_length=15)),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
